# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='twitter_id',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
