# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20160108_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=255)),
                ('two', models.CharField(max_length=255, null=True)),
                ('three', models.CharField(max_length=255, null=True)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
