# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_ngram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngram',
            old_name='one',
            new_name='tag_one',
        ),
        migrations.RenameField(
            model_name='ngram',
            old_name='three',
            new_name='tag_three',
        ),
        migrations.RenameField(
            model_name='ngram',
            old_name='two',
            new_name='tag_two',
        ),
        migrations.AddField(
            model_name='ngram',
            name='token_one',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngram',
            name='token_three',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ngram',
            name='token_two',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
