# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_auto_20160110_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngram',
            name='sentence_starter',
            field=models.BooleanField(default=False),
        ),
    ]
