# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ngram',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.Document'),
        ),
        migrations.AddField(
            model_name='ngram',
            name='twitter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.TwitterUser'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.TwitterUser'),
        ),
    ]
