# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-10 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_remove_ngram_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngram',
            name='tag_one',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ngram',
            name='tag_two',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ngram',
            name='token_one',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ngram',
            name='token_two',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
