# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_twitter_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-twitter_id']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='twitter_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
